name: Depot Bake
description: GitHub Action to build Docker images via Bake with Depot
author: Depot
branding:
  icon: package
  color: gray-dark
runs:
  using: node24
  main: dist/index.js
  post: dist/index.js
inputs:
  build-platform:
    description: 'The platform to use for the build'
    required: false
  buildx-fallback:
    description: 'Fallback to `docker buildx bake` if `depot bake` fails'
    required: false
    default: 'false'
  files:
    description: 'List of bake definition files'
    required: false
  lint:
    description: 'Lint dockerfiles and fail build if any issues are at least the lint-fail-on severity'
    required: false
    default: 'false'
  lint-fail-on:
    description: 'Severity of linter issue to cause the build to fail. (e.g., error, warn, info, none)'
    required: false
  load:
    description: 'Load is a shorthand for --set=*.output=type=docker'
    required: false
    default: 'false'
  no-cache:
    description: 'Do not use cache when building the image'
    required: false
    default: 'false'
  project:
    description: 'Depot project ID'
    required: false
  provenance:
    description: 'Provenance is a shorthand for --set=*.attest=type=provenance'
    required: false
  pull:
    description: 'Always attempt to pull a newer version of the image'
    required: false
    default: 'false'
  push:
    description: 'Push is a shorthand for --set=*.output=type=registry'
    required: false
    default: 'false'
  save:
    description: 'Save the image to the Depot ephemeral registry'
    required: false
    default: 'false'
  save-tag:
    description: 'Additional custom tag for the saved image, use with --save'
    required: false
  sbom:
    description: 'SBOM is a shorthand for --set=*.attest=type=sbom'
    required: false
  sbom-dir:
    description: 'Directory to output SBOMs for each built image'
    required: false
  set:
    description: 'List of targets values to override (eg. targetpattern.key=value)'
    required: false
  targets:
    description: 'List of bake targets'
    required: false
  token:
    description: 'Depot Token used to authenticate with the remote builder instance'
    required: false
  workdir:
    description: 'Working directory of bake execution'
    required: false
    default: '.'
